### ISSUE TITLE
Task List Roadmap

### ISSUE THREAD

**Issue by ffrancoc** [ffrancoc/sgl#1]
- [x] Carga del proyecto
- [ ] Creación de los Modelos
- [ ] Creación de los Repositorios
- [ ] Creación de los Servicios
- [ ] Creación de los Controladores
